version: "3.8"

services:
  mysqldb:
    image: mysql:latest
    restart: unless-stopped
    env_file: ./.env
    environment:
      MYSQL_DATABASE: $MYSQLDB_DATABASE
      MYSQL_USER: $MYSQLDB_USER
      MYSQL_PASSWORD: $MYSQLDB_PASSWORD
      MYSQL_ROOT_PASSWORD: $MYSQLDB_ROOT_PASSWORD
    ports:
      - ${MYSQLDB_LOCAL_PORT}:${MYSQLDB_DOCKER_PORT}
  app:
    depends_on:
      - mysqldb
    restart: on-failure
    image: book-service
    build: .
    env_file: ./.env
    ports:
      - ${SPRING_LOCAL_PORT}:${SPRING_DOCKER_PORT}
      - ${DEBUG_PORT}:${DEBUG_PORT}
    environment:
      SPRING_APPLICATION_JSON: '{
      "spring.datasource.url" : "jdbc:mysql://mysqldb:3306/$MYSQLDB_DATABASE",
      "spring.datasource.username" : "$MYSQLDB_USER",
      "spring.datasource.password" : "$MYSQLDB_PASSWORD",
      "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL8Dialect"
      }'
      JAVA_TOOL_OPTIONLS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"
